export const PHI_PII_PATTERNS: RegExp[] = [
	/\bssn\b/i,
	/\bsocial.?security/i,
	/\btax.?id\b/i,
	/\btin\b/i,
	/\bdate.?of.?birth\b/i,
	/\bdob\b/i,
	/\bbirth.?date\b/i,
	/\bfirst.?name\b/i,
	/\blast.?name\b/i,
	/\bfull.?name\b/i,
	/\bpatient.?name\b/i,
	/\bmember.?name\b/i,
	/\bsubscriber.?name\b/i,
	/\baddress\b/i,
	/\bstreet\b/i,
	/\bcity\b/i,
	/\bzip.?code\b/i,
	/\bpostal.?code\b/i,
	/\bphone\b/i,
	/\btelephone\b/i,
	/\bmobile\b/i,
	/\bcell\b/i,
	/\bfax\b/i,
	/\bemail\b/i,
	/\be.?mail\b/i,
	/\bpassword\b/i,
	/\bsecret\b/i,
	/\btoken\b/i,
	/\bcredential/i,
	/\bauthorization\b/i,
	/\bapi.?key\b/i,
	/\baccess.?key\b/i,
	/\bmedical.?record/i,
	/\bmrn\b/i,
	/\bdiagnosis\b/i,
	/\bdiagnoses\b/i,
	/\bicd.?\d/i,
	/\bcpt\b/i,
	/\bnpi\b/i,
	/\bprovider.?id\b/i,
	/\binsurance.?id\b/i,
	/\bmember.?id\b/i,
	/\bpolicy.?number\b/i,
	/\bgroup.?number\b/i,
	/\bcard.?number\b/i,
	/\baccount.?number\b/i,
	/\brouting.?number\b/i,
	/\biban\b/i,
	/\bswift\b/i,
	/\bcvv\b/i,
	/\bcvc\b/i,
	/\bexpir/i,
	/\bip.?address\b/i,
	/\buser.?agent\b/i,
	/\blatitude\b/i,
	/\blongitude\b/i,
	/\bgeo.?location\b/i,
];

export function isExcludedPath(
	fieldPath: string,
	excludePatterns: RegExp[],
): boolean {
	const normalizedPath = fieldPath.toLowerCase();
	const lastSegment = normalizedPath.split(".").pop() || normalizedPath;
	return excludePatterns.some(
		(pattern) => pattern.test(normalizedPath) || pattern.test(lastSegment),
	);
}
